### PR TITLE
Feature/pastelstatistics hashrate chart

### PR DESCRIPTION
**Pull request by Dinisueldanov**
### Summary
- add hashrate chart page.
- update chart component(theme options).
- add tests for hashrate chart.
### Screenshots
statistics-hashrate-page
hashrate-chart-page

### CODE REVIEW

**Review by ngvtuan — COMMENTED** [review]
update the file name

Please also update the file name, when user download the chart

**Review by ngvtuan — COMMENTED** [review]
price issues
Can we make the USD and BTC prices more clear? Or this is format from API? 

React warning
Can we fix this issue? 
[localhost-1622548881755.log](https://github.com/pastelnetwork/pastel-electron-wallet/files/6576132/localhost-1622548881755.log)

**Review by ngvtuan — COMMENTED** [review]
update number
Can we update the number in the chart?

**Review by ngvtuan — COMMENTED** [review]
When I change the background color of the chart, The line inside the chart changing from the `straight` to the `smoothed curve`. It is only happening with:
- Network Difficulty
- PSL Prices
PSL Prices Yellow
PSL Prices Black
Network Difficulty Yellow
Network Difficulty Black

**Review by ngvtuan — APPROVED** [review]
Final result
https://user-images.githubusercontent.com/10944387/120595226-3cc53000-c46c-11eb-9842-cda0f71a7633.mov

[PSL_difficulty_6_3_2021__13_0.csv](https://github.com/pastelnetwork/pastel-electron-wallet/files/6589289/PSL_difficulty_6_3_2021__13_0.csv)
PSL_difficulty_6_3_2021__13_0
@Dinisueldanov Can you please take a look at this file? It is exported without data. Is this a bug or not? [PSL_prices_6_3_2021__13_0.csv](https://github.com/pastelnetwork/pastel-electron-wallet/files/6589292/PSL_prices_6_3_2021__13_0.csv)
PSL_prices_6_3_2021__13_0
[PSL_hashrate_6_3_2021__13_0.csv](https://github.com/pastelnetwork/pastel-electron-wallet/files/6589293/PSL_hashrate_6_3_2021__13_0.csv)
PSL_hashrate_6_3_2021__13_0


I think this PR is ok to merge after checking the data of `PSL_prices_6_3_2021__13_0.csv` file.

**Review by ngvtuan — APPROVED** [review]

**Review by westalert — APPROVED** [review]

**Pull request merged**
