### PR TITLE
Refactor expert console

### PR DESCRIPTION
**Pull request by westalert**
Refactor expert console

### CODE REVIEW

**Review by br4in3x — APPROVED** [review]

**Comment by br4in3x** [comment]
I think there was an error during the merge. Why I see commits from https://github.com/pastelnetwork/pastel-electron-wallet/pull/61 here? You should reset them to your last commit, merge with master, and force push to fix this.
```
git checkout -b refactor-expert-console-backup; // create a backup of your current branch
git checkout refactor-expert-console; // get back on your branch
git reset --hard 4dea149 // now you are on your last "fix keep terminal state" commit
git pull origin master; // merge master into your branch
git push origin refactor-expert-console --force; // push this changes to this PR overriding commit history
```
If something goes wrong, you still have your `refactor-expert-console-backup` branch.

**Review by br4in3x — CHANGES_REQUESTED** [review]
Please see my comment above

**Comment by westalert** [comment]
> Please see my comment above

Thanks, @br4in3x

**Comment by westalert** [comment]
> I think there was an error during the merge. Why I see commits from #61 here? You should reset them to your last commit, merge with master, and force push to fix this.
> 
> ```
> git checkout -b refactor-expert-console-backup; // create a backup of your current branch
> git checkout refactor-expert-console; // get back on your branch
> git reset --hard 4dea149 // now you are on your last "fix keep terminal state" commit
> git pull origin master; // merge master into your branch, fix any merge conflicts if there are any
> git push origin refactor-expert-console --force; // push this changes to this PR overriding commit history
> ```
> 
> If something goes wrong, you still have your `refactor-expert-console-backup` branch.

Got it.

**Review by br4in3x — APPROVED** [review]

**Pull request merged**
